version: '3.4'

services:


  myinventoryapp:
    container_name: myinventoryappcontainer
    image: ${DOCKER_REGISTRY-}myinventoryapp
    build:
      context: .
      dockerfile: myinventoryapp/Dockerfile
    ports:
      - "5000:80"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://<yourusername>:<yourpassword>@cluster0.mongodb.net/InventoryDb?retryWrites=true&w=majority

  mongo:
    image: mongo
    ports:
      - "27017:27017"

